apiVersion: v1
kind: PersistentVolume

metadata:
  name: first-pv
  labels:
    name: first-pv

spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standart
  hostPath:
    path: /mnt/data